apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: enterprise-app

spec:

  project: default

  source:
    repoURL: https://github.com/company/gitops-repo
    targetRevision: HEAD
    path: kubernetes

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
